name: Bug Report
description: Report a minor bug to us
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please only report issues that are caused by SplameiPlay (so no reports for incorrect file config) and that no-one else has made a duplicate issue
  - type: textarea
    id: description
    attributes:
      label: What went wrong?
      description: Please describe what went wrong with SplameiPlay and what was meant to happen
      placeholder: What went wrong and what has meant to happen
      value: "Some bug description"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type of issue
      description: What type of issue is this bug?
      options:
        - Minor issue (SplameiPlay keeps running)
        - Temp Major issue (SplameiPlay stops running for a bit)
        - Major issue (SplameiPlay stops running permenetly)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Affected version(s)
      description: What versions and groups of SplameiPlay did you get the issue to occur on?
      multiple: true
      options:
        - 5.0 Particle
        - 4.x Bloom
        - 3.x Albedo
      default: 0
    validations:
      required: true
  - type: dropdown
    id: channel
    attributes:
      label: Affected channel(s)
      description: What channels does the issue occur on?
      multiple: true
      options:
        - Stable
        - Beta
        - Alpha
      default: 0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Affected device(s)
      description: When using SplameiPlay, what device(s) have you managed to get the issue to occur on?
      multiple: true
      options:
        - Laptop
        - Dektop PC
        - Mini PC
        - Emulated/Translated Hardware
      default: 0
    validations:
      required: true
  - type: dropdown
    id: osVersion
    attributes:
      label: Affected OS(es)
      description: What different OS versions or software have you been able to get the issue to occur on?
      multiple: true
      options:
        - Windows 10 or 11
        - Pre Windows 10 (i.e 8.x + 7)
        - Wine (or simular app)
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: debugLog
    attributes:
      label: SplameiPlay Log file
      description: Copy and paste the contents of the log file of SplameiPlay found in your AppData Roaming file. This will always be formatted as code so you dont need backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Once you submit this issue, you agree to our [Code of Conduct](https://github.com/splamei/splameiplay/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to the code of conduct, this was made in good faith and no duplicate exists
          required: true
